/**
 * Quranora - Faculty & Teachers Dataset
 */
const teachersData = [
  {
    id: "qari-syed-umar",
    gender: "male",
    nameEn: "Al-Qari Syed Umar Ali",
    nameUr: "القارئ سید عمر علی",
    titleEn: "Lead Qari & Senior Tajweed Specialist",
    titleUr: "چیف قاری و سینئر ماہر تجوید",
    image: "assets/images/qari_syed_umar_ali.jpg",
    experienceEn: "10+ Years Teaching & Tilawat Expertise",
    experienceUr: "10 سال سے زائد تدریسی و تلاوت کا تجربہ",
    qualificationEn: "Shahadat-ul-Alimiyyah & Tajweed Ijazah (Renowned Qari)",
    qualificationUr: "شہادۃ العالمیہ و مستند سندِ قراءت و تجوید",
    languagesEn: "English, Urdu, Arabic",
    languagesUr: "انگلش، اردو، عربی",
    rating: 5.0,
    reviewsCount: 215,
    studentsTaught: "700+ Students Worldwide",
    youtubeUrl: "https://youtube.com/@qarisyedumaraliofficial?si=yOeJAe7XqSURmwrW",
    bioEn: "Renowned Qari known for soul-stirring Tilawat and deep phonetics mastery. Trains students in accurate Makharij, breath control, and melodious recitation.",
    bioUr: "خوش الحان قاری اور مستند استاد جن کی تلاوت قرآن کے دلنشین انداز کو دنیا بھر میں پسند کیا جاتا ہے۔ تجوید اور مخارج کے بہترین ماہر۔",
    audioSampleText: "Listen to Official Tilawat on YouTube",
    audioVerse: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ"
  },
  {
    id: "qari-mueez",
    gender: "male",
    nameEn: "Al-Qari Mueez ur Rehman",
    nameUr: "الشیخ قاری معیز الرحمن الباسط",
    titleEn: "Senior Qari & Qira'at Specialist",
    titleUr: "فاضل قاری و سینئر ماہر قرأت و تجوید",
    image: "assets/images/qari_mueez_ur_rehman.png",
    experienceEn: "9+ Years Teaching & Tilawat Mastery",
    experienceUr: "9 سال سے زائد تدریسی و تجوید کا تجربہ",
    qualificationEn: "Certified Qari (Al-Basit Style) & Tajweed Ijazah",
    qualificationUr: "شہادت و سندِ قراءت و تجوید باسلوبِ عبدالباسط",
    languagesEn: "English, Urdu, Arabic",
    languagesUr: "انگلش، اردو، عربی",
    rating: 4.98,
    reviewsCount: 195,
    studentsTaught: "580+ Students Worldwide",
    youtubeUrl: "https://youtube.com/@alqarimueezurrehman?si=OWMnUcMmC2T-0KlJ",
    bioEn: "Distinguished Qari celebrated for melodic Tilawat in the classical tradition. Specializes in advanced Tajweed rules, Maqamat, and beautiful Quran recitation.",
    bioUr: "خوش الحان قاری جن کی مسحور کن تلاوت اور اندازِ بیاں کو خاص پذیرائی حاصل ہے۔ تجوید، تلفظ اور مخارج کے بہترین اتالیق۔",
    audioSampleText: "Listen to Official Tilawat on YouTube",
    audioVerse: "اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ"
  },
  {
    id: "maulana-ammar-shah",
    gender: "male",
    nameEn: "Maulana Syed Ammar Hussain Shah",
    nameUr: "مولانا سید عمار حسین شاہ",
    titleEn: "Senior Islamic Scholar & Tafseer Specialist",
    titleUr: "سینئر عالمِ دین و نگران شعبہ ترجمہ و تفسیر",
    image: "assets/images/maulana_syed_ammar_shah.png",
    experienceEn: "8+ Years in Quranic & Islamic Higher Education",
    experienceUr: "8 سال سے زائد تدریسی و علمی تجربہ",
    qualificationEn: "Shahadat-ul-Alimiyyah (Dars-e-Nizami) & M.Phil in Islamic Studies",
    qualificationUr: "عالمِ دین (شہادۃ العالمیہ) و ایم فل اسلامیات",
    languagesEn: "English, Urdu, Arabic",
    languagesUr: "انگلش، اردو، عربی",
    rating: 5.0,
    reviewsCount: 178,
    studentsTaught: "450+ Students Worldwide",
    bioEn: "Accomplished Aalim and M.Phil Islamic scholar. Expert in guiding adult learners and youth through Quran Translation (Tarjuma), Tafseer, Hadith studies, and Islamic Jurisprudence (Fiqh).",
    bioUr: "مستند عالمِ دین و ایم فل اسکالر۔ ترجمہ و تفسیرِ قرآن، فہمِ حدیث، فقہی احکام اور نوجوان نسل کی فکری و اسلامی تربیت کے ممتاز استاد۔",
    audioSampleText: "Surah Al-Fatiha (Tarjuma & Tafseer Recitation)",
    audioVerse: "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ"
  },
  {
    id: "qari-hasnain-muavia",
    gender: "male",
    nameEn: "Qari Hasnain Muavia",
    nameUr: "القارئ حسنین معاویہ",
    titleEn: "Hifz-ul-Quran Specialist & Tajweed Instructor",
    titleUr: "استاد شعبہ حفظِ قرآن و ماہر تجوید",
    image: "assets/images/qari_hasnain_muavia.jpg",
    experienceEn: "4+ Years Teaching Hifz & Quranic Studies",
    experienceUr: "4 سال سے زائد حفظ و تدریسِ قرآن کا تجربہ",
    qualificationEn: "Hafiz-ul-Quran & Certified Qari (Tajweed Ijazah)",
    qualificationUr: "حافظِ قرآن و سندِ قراءت و تجوید القرآن",
    languagesEn: "English, Urdu, Arabic",
    languagesUr: "انگلش، اردو، عربی",
    rating: 4.98,
    reviewsCount: 142,
    studentsTaught: "250+ Huffaz & Students Mentored",
    bioEn: "Dedicated Hifz-ul-Quran instructor with 4 years of proven experience guiding students through systematic memorization, daily Sabaq, Sabqi, and Manzil revision with accurate Tajweed.",
    bioUr: "گزشتہ 4 سال سے شعبہ حفظ القرآن سے وابستہ۔ طلبہ کو آسان فہم انداز میں سبق، سبقی اور منزل کی پختگی کے ساتھ حفظ کروانے اور تجوید سکھانے کے ماہر۔",
    audioSampleText: "Surah Al-Mulk (Hifz Recitation)",
    audioVerse: "تَبَارَكَ الَّذِي بِيَدِهِ الْمُلْكُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ"
  },
  {
    id: "ustadha-maryam",
    gender: "female",
    nameEn: "Ustadha Maryam Fatima",
    nameUr: "استاذہ مریم فاطمہ",
    titleEn: "Lead Female Tajweed & Noorani Qaida Instructor",
    titleUr: "سینئر معلمہ برائے تجوید و ناظرہ",
    image: "assets/images/teacher_female_1.jpg",
    experienceEn: "8+ Years Teaching Global Students",
    experienceUr: "8 سال سے زائد آن لائن تدریسی تجربہ",
    qualificationEn: "M.A. Islamic Studies & Certified Qaria with Tajweed Sanad",
    qualificationUr: "ایم اے اسلامیات، فاضلہ درس نظامی و باقاعدہ سندِ تجوید",
    languagesEn: "English, Urdu",
    languagesUr: "انگلش، اردو",
    rating: 4.99,
    reviewsCount: 189,
    studentsTaught: "620+ Students",
    bioEn: "Specialized in teaching sisters and young girls. Highly celebrated by overseas mothers for her warm, encouraging, and structured pedagogy.",
    bioUr: "بہنوں اور بچیوں کے لیے مخصوص کلاسز۔ غیر ملکی مسلم والدین کی طرف سے انتہائی پسندیدہ اور بااعتماد معلمہ۔",
    audioSampleText: "Surah Ad-Duha (Tajweed Recitation)",
    audioVerse: "وَالضُّحَىٰ وَاللَّيْلِ إِذَا سَجَىٰ"
  },
  {
    id: "qari-tariq",
    gender: "male",
    nameEn: "Qari Tariq Mahmood",
    nameUr: "قاری طارق محمود",
    titleEn: "Head of Hifz-ul-Quran & Revision Department",
    titleUr: "نگران شعبہ حفظِ قرآن و تکرار",
    image: "assets/images/teacher_male_2.jpg",
    experienceEn: "12+ Years in Quranic Memorization",
    experienceUr: "12 سالہ تجربہ حفظ و نگرانی",
    qualificationEn: "Hafiz-ul-Quran, Wifaq-ul-Madaris Gold Medalist",
    qualificationUr: "حافظِ قرآن، وفاق المدارس العربیہ سے امتیازی سند",
    languagesEn: "English, Urdu, Arabic",
    languagesUr: "انگلش، اردو، عربی",
    rating: 4.96,
    reviewsCount: 110,
    studentsTaught: "380+ Huffaz Mentored",
    bioEn: "Has guided dozens of overseas students to complete full Quran memorization with ironclad retention techniques.",
    bioUr: "درجنوں طلبہ کو مکمل حفظ قرآن مکمل کروایا۔ سبق، سبقی اور منزل کو پختہ کروانے کی خصوصی مہارت۔",
    audioSampleText: "Surah Ar-Rahman (Murattal)",
    audioVerse: "الرَّحْمَٰنُ عَلَّمَ الْقُرْآنَ"
  },
  {
    id: "ustadha-aisha",
    gender: "female",
    nameEn: "Ustadha Aisha Siddiqa",
    nameUr: "استاذہ عائشہ صدیقہ",
    titleEn: "Kids Quran & Islamic Akhlaq Specialist",
    titleUr: "ماہر اطفال قرآنی تربیت و اخلاقیات",
    image: "assets/images/teacher_female_2.jpg",
    experienceEn: "6+ Years in Early Childhood Quran Teaching",
    experienceUr: "6 سالہ تجربہ برائے اطفال",
    qualificationEn: "B.S. Islamic Education & Child Psychology Certified",
    qualificationUr: "بی ایس اسلامک ایجوکیشن و چائلڈ لرننگ ڈپلومہ",
    languagesEn: "English, Urdu",
    languagesUr: "انگلش، اردو",
    rating: 4.99,
    reviewsCount: 165,
    studentsTaught: "510+ Young Learners",
    bioEn: "Makes Quran learning enjoyable for 4-10 year olds through friendly gamified learning, positive reinforcement, and engaging stories.",
    bioUr: "چھوٹے بچوں کو محبت، دوستانہ انداز اور دلچسپ سرگرمیوں کے ساتھ قاعدہ اور دعائیں سکھانے کی ماہر۔",
    audioSampleText: "Surah Al-Ikhlas & Daily Dua",
    audioVerse: "قُلْ هُوَ اللَّهُ أَحَدٌ"
  }
];
