/**
 * Quranora - Comprehensive Quran Metadata
 * 114 Surahs, 30 Juz, Tajweed Categories
 */

const QURAN_SURAHS = [
  { number: 1, name: "Al-Fatihah", arabic: "الفاتحة", english: "The Opening", ayahs: 7, type: "Meccan", juz: 1 },
  { number: 2, name: "Al-Baqarah", arabic: "البقرة", english: "The Cow", ayahs: 286, type: "Medinan", juz: 1 },
  { number: 3, name: "Ali 'Imran", arabic: "آل عمران", english: "Family of Imran", ayahs: 200, type: "Medinan", juz: 3 },
  { number: 4, name: "An-Nisa", arabic: "النساء", english: "The Women", ayahs: 176, type: "Medinan", juz: 4 },
  { number: 5, name: "Al-Ma'idah", arabic: "المائدة", english: "The Table Spread", ayahs: 120, type: "Medinan", juz: 6 },
  { number: 6, name: "Al-An'am", arabic: "الأنعام", english: "The Cattle", ayahs: 165, type: "Meccan", juz: 7 },
  { number: 7, name: "Al-A'raf", arabic: "الأعراف", english: "The Heights", ayahs: 206, type: "Meccan", juz: 8 },
  { number: 8, name: "Al-Anfal", arabic: "الأنفال", english: "The Spoils of War", ayahs: 75, type: "Medinan", juz: 9 },
  { number: 9, name: "At-Tawbah", arabic: "التوبة", english: "The Repentance", ayahs: 129, type: "Medinan", juz: 10 },
  { number: 10, name: "Yunus", arabic: "يونس", english: "Jonah", ayahs: 109, type: "Meccan", juz: 11 },
  { number: 11, name: "Hud", arabic: "هود", english: "Hud", ayahs: 123, type: "Meccan", juz: 11 },
  { number: 12, name: "Yusuf", arabic: "يوسف", english: "Joseph", ayahs: 111, type: "Meccan", juz: 12 },
  { number: 13, name: "Ar-Ra'd", arabic: "الرعد", english: "The Thunder", ayahs: 43, type: "Medinan", juz: 13 },
  { number: 14, name: "Ibrahim", arabic: "إبراهيم", english: "Abraham", ayahs: 52, type: "Meccan", juz: 13 },
  { number: 15, name: "Al-Hijr", arabic: "الحجر", english: "The Rocky Tract", ayahs: 99, type: "Meccan", juz: 14 },
  { number: 16, name: "An-Nahl", arabic: "النحل", english: "The Bee", ayahs: 128, type: "Meccan", juz: 14 },
  { number: 17, name: "Al-Isra", arabic: "الإسراء", english: "The Night Journey", ayahs: 111, type: "Meccan", juz: 15 },
  { number: 18, name: "Al-Kahf", arabic: "الكهف", english: "The Cave", ayahs: 110, type: "Meccan", juz: 15 },
  { number: 19, name: "Maryam", arabic: "مريم", english: "Mary", ayahs: 98, type: "Meccan", juz: 16 },
  { number: 20, name: "Taha", arabic: "طه", english: "Ta-Ha", ayahs: 135, type: "Meccan", juz: 16 },
  { number: 21, name: "Al-Anbiya", arabic: "الأنبياء", english: "The Prophets", ayahs: 112, type: "Meccan", juz: 17 },
  { number: 22, name: "Al-Hajj", arabic: "الحج", english: "The Pilgrimage", ayahs: 78, type: "Medinan", juz: 17 },
  { number: 23, name: "Al-Mu'minun", arabic: "المؤمنون", english: "The Believers", ayahs: 118, type: "Meccan", juz: 18 },
  { number: 24, name: "An-Nur", arabic: "النور", english: "The Light", ayahs: 64, type: "Medinan", juz: 18 },
  { number: 25, name: "Al-Furqan", arabic: "الفرقان", english: "The Criterion", ayahs: 77, type: "Meccan", juz: 18 },
  { number: 26, name: "Ash-Shu'ara", arabic: "الشعراء", english: "The Poets", ayahs: 227, type: "Meccan", juz: 19 },
  { number: 27, name: "An-Naml", arabic: "النمل", english: "The Ant", ayahs: 93, type: "Meccan", juz: 19 },
  { number: 28, name: "Al-Qasas", arabic: "القصص", english: "The Stories", ayahs: 88, type: "Meccan", juz: 20 },
  { number: 29, name: "Al-'Ankabut", arabic: "العنكبوت", english: "The Spider", ayahs: 69, type: "Meccan", juz: 20 },
  { number: 30, name: "Ar-Rum", arabic: "الروم", english: "The Romans", ayahs: 60, type: "Meccan", juz: 21 },
  { number: 31, name: "Luqman", arabic: "لقمان", english: "Luqman", ayahs: 34, type: "Meccan", juz: 21 },
  { number: 32, name: "As-Sajdah", arabic: "السجدة", english: "The Prostration", ayahs: 30, type: "Meccan", juz: 21 },
  { number: 33, name: "Al-Ahzab", arabic: "الأحزاب", english: "The Combined Forces", ayahs: 73, type: "Medinan", juz: 21 },
  { number: 34, name: "Saba", arabic: "سبأ", english: "Sheba", ayahs: 54, type: "Meccan", juz: 22 },
  { number: 35, name: "Fatir", arabic: "فاطر", english: "Originator", ayahs: 45, type: "Meccan", juz: 22 },
  { number: 36, name: "Ya-Sin", arabic: "يس", english: "Ya Sin", ayahs: 83, type: "Meccan", juz: 22 },
  { number: 37, name: "As-Saffat", arabic: "الصافات", english: "Those who set the Ranks", ayahs: 182, type: "Meccan", juz: 23 },
  { number: 38, name: "Sad", arabic: "ص", english: "The Letter Sad", ayahs: 88, type: "Meccan", juz: 23 },
  { number: 39, name: "Az-Zumar", arabic: "الزمر", english: "The Troops", ayahs: 75, type: "Meccan", juz: 23 },
  { number: 40, name: "Ghafir", arabic: "غافر", english: "The Forgiver", ayahs: 85, type: "Meccan", juz: 24 },
  { number: 41, name: "Fussilat", arabic: "فصلت", english: "Explained in Detail", ayahs: 54, type: "Meccan", juz: 24 },
  { number: 42, name: "Ash-Shura", arabic: "الشورى", english: "The Consultation", ayahs: 53, type: "Meccan", juz: 25 },
  { number: 43, name: "Az-Zukhruf", arabic: "الزخرف", english: "The Ornaments of Gold", ayahs: 89, type: "Meccan", juz: 25 },
  { number: 44, name: "Ad-Dukhan", arabic: "الدخان", english: "The Smoke", ayahs: 59, type: "Meccan", juz: 25 },
  { number: 45, name: "Al-Jathiyah", arabic: "الجاثية", english: "The Crouching", ayahs: 37, type: "Meccan", juz: 25 },
  { number: 46, name: "Al-Ahqaf", arabic: "الأحقاف", english: "The Wind-Curved Sandhills", ayahs: 35, type: "Meccan", juz: 26 },
  { number: 47, name: "Muhammad", arabic: "محمد", english: "Muhammad", ayahs: 38, type: "Medinan", juz: 26 },
  { number: 48, name: "Al-Fath", arabic: "الفتح", english: "The Victory", ayahs: 29, type: "Medinan", juz: 26 },
  { number: 49, name: "Al-Hujurat", arabic: "الحجرات", english: "The Rooms", ayahs: 18, type: "Medinan", juz: 26 },
  { number: 50, name: "Qaf", arabic: "ق", english: "The Letter Qaf", ayahs: 45, type: "Meccan", juz: 26 },
  { number: 51, name: "Adh-Dhariyat", arabic: "الذاريات", english: "The Winnowing Winds", ayahs: 60, type: "Meccan", juz: 26 },
  { number: 52, name: "At-Tur", arabic: "الطور", english: "The Mount", ayahs: 49, type: "Meccan", juz: 27 },
  { number: 53, name: "An-Najm", arabic: "النجم", english: "The Star", ayahs: 62, type: "Meccan", juz: 27 },
  { number: 54, name: "Al-Qamar", arabic: "القمر", english: "The Moon", ayahs: 55, type: "Meccan", juz: 27 },
  { number: 55, name: "Ar-Rahman", arabic: "الرحمن", english: "The Beneficent", ayahs: 78, type: "Medinan", juz: 27 },
  { number: 56, name: "Al-Waqi'ah", arabic: "الواقعة", english: "The Inevitable", ayahs: 96, type: "Meccan", juz: 27 },
  { number: 57, name: "Al-Hadid", arabic: "الحديد", english: "The Iron", ayahs: 29, type: "Medinan", juz: 27 },
  { number: 58, name: "Al-Mujadila", arabic: "المجادلة", english: "The Pleading Woman", ayahs: 22, type: "Medinan", juz: 28 },
  { number: 59, name: "Al-Hashr", arabic: "الحشر", english: "The Exile", ayahs: 24, type: "Medinan", juz: 28 },
  { number: 60, name: "Al-Mumtahanah", arabic: "الممتحنة", english: "She that is to be examined", ayahs: 13, type: "Medinan", juz: 28 },
  { number: 61, name: "As-Saff", arabic: "الصف", english: "The Ranks", ayahs: 14, type: "Medinan", juz: 28 },
  { number: 62, name: "Al-Jumu'ah", arabic: "الجمعة", english: "The Congregation", ayahs: 11, type: "Medinan", juz: 28 },
  { number: 63, name: "Al-Munafiqun", arabic: "المنافقون", english: "The Hypocrites", ayahs: 11, type: "Medinan", juz: 28 },
  { number: 64, name: "At-Taghabun", arabic: "التغابن", english: "The Mutual Disillusion", ayahs: 18, type: "Medinan", juz: 28 },
  { number: 65, name: "At-Talaq", arabic: "الطلاق", english: "The Divorce", ayahs: 12, type: "Medinan", juz: 28 },
  { number: 66, name: "At-Tahrim", arabic: "التحريم", english: "The Prohibition", ayahs: 12, type: "Medinan", juz: 28 },
  { number: 67, name: "Al-Mulk", arabic: "الملك", english: "The Sovereignty", ayahs: 30, type: "Meccan", juz: 29 },
  { number: 68, name: "Al-Qalam", arabic: "القلم", english: "The Pen", ayahs: 52, type: "Meccan", juz: 29 },
  { number: 69, name: "Al-Haqqah", arabic: "الحاقة", english: "The Reality", ayahs: 52, type: "Meccan", juz: 29 },
  { number: 70, name: "Al-Ma'arij", arabic: "المعارج", english: "The Ascending Stairways", ayahs: 44, type: "Meccan", juz: 29 },
  { number: 71, name: "Nuh", arabic: "نوح", english: "Noah", ayahs: 28, type: "Meccan", juz: 29 },
  { number: 72, name: "Al-Jinn", arabic: "الجن", english: "The Jinn", ayahs: 28, type: "Meccan", juz: 29 },
  { number: 73, name: "Al-Muzzammil", arabic: "المزمل", english: "The Enshrouded One", ayahs: 20, type: "Meccan", juz: 29 },
  { number: 74, name: "Al-Muddaththir", arabic: "المدثر", english: "The Cloaked One", ayahs: 56, type: "Meccan", juz: 29 },
  { number: 75, name: "Al-Qiyamah", arabic: "القيامة", english: "The Resurrection", ayahs: 40, type: "Meccan", juz: 29 },
  { number: 76, name: "Al-Insan", arabic: "الإنسان", english: "The Human", ayahs: 31, type: "Medinan", juz: 29 },
  { number: 77, name: "Al-Mursalat", arabic: "المرسلات", english: "The Emissaries", ayahs: 50, type: "Meccan", juz: 29 },
  { number: 78, name: "An-Naba", arabic: "النبأ", english: "The Tidings", ayahs: 40, type: "Meccan", juz: 30 },
  { number: 79, name: "An-Nazi'at", arabic: "النازعات", english: "Those who drag forth", ayahs: 46, type: "Meccan", juz: 30 },
  { number: 80, name: "'Abasa", arabic: "عبس", english: "He Frowned", ayahs: 42, type: "Meccan", juz: 30 },
  { number: 81, name: "At-Takwir", arabic: "التكوير", english: "The Overthrowing", ayahs: 29, type: "Meccan", juz: 30 },
  { number: 82, name: "Al-Infitar", arabic: "الانفطار", english: "The Cleaving", ayahs: 19, type: "Meccan", juz: 30 },
  { number: 83, name: "Al-Mutaffifin", arabic: "المطففين", english: "The Defrauding", ayahs: 36, type: "Meccan", juz: 30 },
  { number: 84, name: "Al-Inshiqaq", arabic: "الانشقاق", english: "The Splitting Open", ayahs: 25, type: "Meccan", juz: 30 },
  { number: 85, name: "Al-Buruj", arabic: "البروج", english: "The Mansions of the Stars", ayahs: 22, type: "Meccan", juz: 30 },
  { number: 86, name: "At-Tariq", arabic: "الطارق", english: "The Nightcomer", ayahs: 17, type: "Meccan", juz: 30 },
  { number: 87, name: "Al-A'la", arabic: "الأعلى", english: "The Most High", ayahs: 19, type: "Meccan", juz: 30 },
  { number: 88, name: "Al-Ghashiyah", arabic: "الغاشية", english: "The Overwhelming", ayahs: 26, type: "Meccan", juz: 30 },
  { number: 89, name: "Al-Fajr", arabic: "الفجر", english: "The Dawn", ayahs: 30, type: "Meccan", juz: 30 },
  { number: 90, name: "Al-Balad", arabic: "البلد", english: "The City", ayahs: 20, type: "Meccan", juz: 30 },
  { number: 91, name: "Ash-Shams", arabic: "الشمس", english: "The Sun", ayahs: 15, type: "Meccan", juz: 30 },
  { number: 92, name: "Al-Layl", arabic: "الليل", english: "The Night", ayahs: 21, type: "Meccan", juz: 30 },
  { number: 93, name: "Ad-Duhaa", arabic: "الضحى", english: "The Morning Hours", ayahs: 11, type: "Meccan", juz: 30 },
  { number: 94, name: "Ash-Sharh", arabic: "الشرح", english: "The Relief", ayahs: 8, type: "Meccan", juz: 30 },
  { number: 95, name: "At-Tin", arabic: "التين", english: "The Fig", ayahs: 8, type: "Meccan", juz: 30 },
  { number: 96, name: "Al-'Alaq", arabic: "العلق", english: "The Clot", ayahs: 19, type: "Meccan", juz: 30 },
  { number: 97, name: "Al-Qadr", arabic: "القدر", english: "The Power", ayahs: 5, type: "Meccan", juz: 30 },
  { number: 98, name: "Al-Bayyinah", arabic: "البينة", english: "The Clear Proof", ayahs: 8, type: "Medinan", juz: 30 },
  { number: 99, name: "Az-Zalzalah", arabic: "الزلزلة", english: "The Earthquake", ayahs: 8, type: "Medinan", juz: 30 },
  { number: 100, name: "Al-'Adiyat", arabic: "العاديات", english: "The Courser", ayahs: 11, type: "Meccan", juz: 30 },
  { number: 101, name: "Al-Qari'ah", arabic: "القارعة", english: "The Calamity", ayahs: 11, type: "Meccan", juz: 30 },
  { number: 102, name: "At-Takathur", arabic: "التكاثر", english: "The Rivalry in world increase", ayahs: 8, type: "Meccan", juz: 30 },
  { number: 103, name: "Al-'Asr", arabic: "العصر", english: "The Declining Day", ayahs: 3, type: "Meccan", juz: 30 },
  { number: 104, name: "Al-Humazah", arabic: "الهمزة", english: "The Traducer", ayahs: 9, type: "Meccan", juz: 30 },
  { number: 105, name: "Al-Fil", arabic: "الفيل", english: "The Elephant", ayahs: 5, type: "Meccan", juz: 30 },
  { number: 106, name: "Quraysh", arabic: "قريش", english: "Quraysh", ayahs: 4, type: "Meccan", juz: 30 },
  { number: 107, name: "Al-Ma'un", arabic: "الماعون", english: "The Small Kindness", ayahs: 7, type: "Meccan", juz: 30 },
  { number: 108, name: "Al-Kawthar", arabic: "الكوثر", english: "The Abundance", ayahs: 3, type: "Meccan", juz: 30 },
  { number: 109, name: "Al-Kafirun", arabic: "الكافرون", english: "The Disbelievers", ayahs: 6, type: "Meccan", juz: 30 },
  { number: 110, name: "An-Nasr", arabic: "النصر", english: "The Divine Support", ayahs: 3, type: "Medinan", juz: 30 },
  { number: 111, name: "Al-Masad", arabic: "المسد", english: "The Palm Fiber", ayahs: 5, type: "Meccan", juz: 30 },
  { number: 112, name: "Al-Ikhlas", arabic: "الإخلاص", english: "The Sincerity", ayahs: 4, type: "Meccan", juz: 30 },
  { number: 113, name: "Al-Falaq", arabic: "الفلق", english: "The Daybreak", ayahs: 5, type: "Meccan", juz: 30 },
  { number: 114, name: "An-Nas", arabic: "الناس", english: "Mankind", ayahs: 6, type: "Meccan", juz: 30 }
];

const JUZ_LIST = Array.from({ length: 30 }, (_, i) => ({
  juzNumber: i + 1,
  title: `Juz ${i + 1}`,
  arabic: `الجزء ${i + 1}`
}));

const TAJWEED_RULES = [
  { code: "NOON_GHUNNAH", title: "Ghunnah on Noon & Meem Mushaddad", category: "Ghunnah" },
  { code: "IKHFA", title: "Ikhfa (Hiding) of Noon Sakinah", category: "Noon Sakinah" },
  { code: "IDGHAM", title: "Idgham with & without Ghunnah", category: "Noon Sakinah" },
  { code: "IZHAR", title: "Izhar Halqi (Clear pronunciation)", category: "Noon Sakinah" },
  { code: "IQLAB", title: "Iqlab (Converting to Meem)", category: "Noon Sakinah" },
  { code: "QALQALAH", title: "Qalqalah (Echoing consonants قطب جد)", category: "Echoing" },
  { code: "MADD_ASLI", title: "Madd Asli / Tabee'i (Natural elongation 2 Harakah)", category: "Madd" },
  { code: "MADD_MUTTASIL", title: "Madd Muttasil (Connected Madd 4-5 Harakah)", category: "Madd" },
  { code: "MADD_MUNFASIL", title: "Madd Munfasil (Separated Madd 4-5 Harakah)", category: "Madd" },
  { code: "MADD_LAZIM", title: "Madd Lazim (Compulsory Madd 6 Harakah)", category: "Madd" },
  { code: "MAKHRAJ_HALQ", title: "Throat letters (Halqi)", category: "Makharij" },
  { code: "MAKHRAJ_LISAN", title: "Tongue articulation points (Lisan)", category: "Makharij" },
  { code: "TAFKEEM_TARQEEQ", title: "Heavy (Tafkheem) vs Light (Tarqeeq) letters", category: "Characteristics" }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { QURAN_SURAHS, JUZ_LIST, TAJWEED_RULES };
} else {
  window.QuranMeta = { QURAN_SURAHS, JUZ_LIST, TAJWEED_RULES };
}
